# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designed.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 574)
        MainWindow.setStyleSheet(
            "QWidget {\n"
            "    background-color: #e4e6b5;\n"
            "    color: #fff;\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    font-size: 18px;\n"
            "    background-color: rgba(255, 255, 255, 0.0);\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "    background-color: #bec18a;\n"
            "    color: #fff;\n"
            "    border: none;\n"
            "    padding: 8px 16px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #b1b463;\n"
            "}\n"
        "")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(230, 50, 651, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 490, 166, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 530, 166, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 231, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/summer.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 10, 171, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 10, 171, 31))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "Передбачити"))
        self.pushButton_7.setText(_translate("MainWindow", "Всі дані"))
        self.pushButton_4.setText(_translate("MainWindow", "Графік 1"))
        self.pushButton_3.setText(_translate("MainWindow", "Графік 2"))
